enable-magisk-update = false
parallel-jobs = 1

[YouTube]
build-mode = "apk"
excluded-patches = "'Custom branding' 'Change header' 'Announcements' 'Downloads' 'Enable debugging'"
included-patches = ""
version = "auto"
arch = "all"  
riplib = true 
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
excluded-patches = ""
included-patches = ""
riplib = true 
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Messenger]
enabled = true
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
excluded-patches = "'Hide inbox subtabs' 'Disable typing indicator'"
arch = "arm64-v8a"
riplib = true
