enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = "'Custom branding' 'Change header' 'Announcements' 'Downloads' 'Enable debugging'"
included-patches = ""
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Translations for YouTube'"
included-patches = "'Visual preferences icons'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Messenger]
enabled = true
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
excluded-patches = "'Hide inbox subtabs' 'Disable typing indicator'"
arch = "arm64-v8a"
